matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - brew update
  - brew install python3
  - pip3 install -U setuptools

install: python3 setup.py install

script: python3 test.py

after_success: travis/build-bottle.sh
