matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3; fi
  - pip3 install -U setuptools

install:
  - if [[ -z "$DOCKER_IMAGE" ]]; then python3 setup.py install; fi
  - if [[ -n "$DOCKER_IMAGE" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/manylinux-build.sh; fi

script: if [[ -z "$DOCKER_IMAGE" ]]; then python3 test.py; else ls wheelhouse/*; fi

after_success:
  - travis/distribute.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis/build-bottle.sh; fi
